apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-cd-pipeline-run-
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
